### ISSUE TITLE
Port to serde

### ISSUE THREAD

**Issue by softprops** [softprops/shiplift#10]
https://github.com/serde-rs/serde/pull/204#issuecomment-172259464

**Comment by softprops** [comment]
0.7 was just released with everything we were waiting for

**Comment by softprops** [comment]
https://erickt.github.io/blog/2016/02/26/serde-0-dot-7/

**Comment by shulcsm** [comment]
Hey i'm willing to do this. However i'm new to rust and not sure about whole HashMap param situation. Can spell out structs so we have concrete fields on repr and builder?

**Comment by matthiasbeyer** [comment]
Please do this. :-/

**Comment by abusch** [comment]
It looks like this is already done and can be closed?

**Comment by softprops** [comment]
Good call!

**Comment by abusch** [comment]
Looking at it, I think I may have been mistaken. I thought it had been migrated because I saw the serde dependency in Cargo.toml, but the code still seems to be using rustc_serialize... Sorry for the confusion :(
