### ISSUE TITLE
Make the API asynchronous

### ISSUE THREAD

**Issue by abusch** [softprops/shiplift#111]
Since we're using hyper under the hood, which is fully async, it is a bit of a shame that shiplift's API isn't. It would be great to change the methods that make a call to Docker to return a `Future` of some kind.

Some examples of Rust crates with an Async API:
* [fantoccini](https://github.com/jonhoo/fantoccini)
* [tokio-zookeeper](https://github.com/jonhoo/tokio-zookeeper)

Maybe for version 0.5? :)

**Comment by softprops** [comment]
I agree. This should be pretty straight forward There are many calls to [block_on](https://github.com/softprops/shiplift/blob/master/src/transport.rs#L195) that seem unnecessary.

**Comment by abusch** [comment]
I've been working on it and am slowly making progress. Still a few methods to do, and some clean-up, but the `stats` example works and properly streams `Stats` objects as they're received, which I'm quite happy about :) You can see the work in progress here: https://github.com/abusch/shiplift/tree/async_api
