### ISSUE TITLE
Library broken by recent changes.

### ISSUE THREAD

**Issue by Nurrl** [softprops/shiplift#123]
- Crate version: master
- OS: Linux x64
- Output of running `docker version` on the command line:
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Sun, 16 Sep 2018 13:21:33 +1000
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Sun Sep 16 03:21:33 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

So as in the title, the recent changes broke the `Images::pull()` which results in a: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeJsonError(Error("invalid type: map, expected a sequence", line: 1, column: 1))', libcore/result.rs:945:5
```
for no reason, but the download occurs, it successfully pulls the image.
And after that, `Containers::create()` fails with `Config cannot be empty in order to create a container` when the config is actually not empty:
```rust
&ContainerOptionsBuilder::new("redis:latest")
        .name("test-name").build()
```

All that seems really weird to me..

**Comment by Nurrl** [comment]
Fixed the second issue, sending PR asap.

**Comment by softprops** [comment]
Note there a number of changes recently folded into master the upcoming release https://github.com/softprops/shiplift/blob/master/CHANGELOG.md. sorry if this caught you off gaurd. And pulls are def welcome!

**Comment by Nurrl** [comment]
@FauxFaux, That's what I was noticing, I'm gonna try it out !

**Comment by FauxFaux** [comment]
I have it working, give me a minute!

**Comment by Nurrl** [comment]
Oh nice !

**Comment by FauxFaux** [comment]
Mmm. This new API is not great for `build()`, as it now only returns results at the end of the build, not live progress.

**Comment by Nurrl** [comment]
We said the same but in different places :,)

**Comment by Nurrl** [comment]
Let's continue the talk here, #126 should be merged for now since it fixes the issue temporarily.

**Comment by Nurrl** [comment]
But #126 should't close this issue anymore. Because it's not a perfect integration.
