### ISSUE TITLE
How to run a background container, like --detach?

### ISSUE THREAD

**Issue by Escapingbug** [softprops/shiplift#131]
I'm not sure if i get this right, but I'm not seeing anything about this.. So how can I do something like this?

**Comment by bossmc** [comment]
On the docker daemon API, all containers are created detatched, and you have to attach to them if you wish to.  The docker CLI defaults to the reverse behaviour, which is nice and confusing.  

Simple answer, you don't have to do anything special to create a detached container, just use the `create` and `start` functions and you're golden.

**Comment by mfirry** [comment]
sorry to reply here... will `create` and `start` be effectively the way to do `docker run`?

**Comment by bossmc** [comment]
`create` and `start` are equivalent to `docker run -d` - if you want to do something like `docker run` you'll need to `attach` (or `attach_blocking`) too.

https://docs.rs/shiplift/0.5.0/shiplift/struct.Container.html#method.attach
