### ISSUE TITLE
Support autherntication with tokens

### ISSUE THREAD

**Issue by keirlawson** [softprops/shiplift#159]
From the API docs it looks like it is only possible to authenticate with registries using a username/password, however if is using a credential helper to generate their credential this may return an Identity token.  Whilst I would imagine interacting with credential helpers is out of scope for this library, exposing a means of authenticating based on a token would enable the use of tokens retrieved by these means.

**Comment by softprops** [comment]
@keirlawson I just published a new release with a bunch of recent changes https://github.com/softprops/shiplift/blob/master/CHANGELOG.md#050 including a registry auth change https://github.com/softprops/shiplift/pull/157. Does this change cover the usecase you are  bumping into?

**Comment by keirlawson** [comment]
Yep, perfect!
