### ISSUE TITLE
Serialize is defined multiple times

### ISSUE THREAD

**Issue by Ralvke** [softprops/shiplift#160]
The version at crates.io has a [bug](https://github.com/softprops/shiplift/blob/0.4.0/src/builder.rs#L4-L5) (`Serialize is defined multiple times`). 
Seems like it has [already fixed](https://github.com/softprops/shiplift/blob/master/src/builder.rs#L4), but don't pulled into crates.io. Please do it

- Crate version: 0.4
- OS: Linux

**Comment by softprops** [comment]
published a new release what should include that fix https://github.com/softprops/shiplift/blob/master/CHANGELOG.md#050
