### ISSUE TITLE
Support for publish?

### ISSUE THREAD

**Issue by gwihlidal** [softprops/shiplift#161]
There is an expose method on the container builder, but there is no way (it appears) to publish a port, which is an important feature - see: https://medium.freecodecamp.org/expose-vs-publish-docker-port-commands-explained-simply-434593dbc9a3

Is this a known issue? It would be awesome to get publish added to the options.

Thank you!

**Comment by gwihlidal** [comment]
It looks like HostConfig.PortBindings is specified by expose(), but ExposedPorts is not?
https://stackoverflow.com/questions/20428302/binding-a-port-to-a-host-interface-using-the-rest-api

If I run my container from the cmd line:
```
docker run --detach --publish 63999:63999 --name svc-test-cmd my_image
```

vs from shiplift:
```
let fut = docker
        .containers()
        .create(&shiplift::ContainerOptions::builder("my_image")
        .name("svc-test-shiplift")
        .expose(63999, "", 63999)
        .build())
        .map(|info| println!("{:?}", info))
        .map_err(|e| eprintln!("Error: {}", e));
    tokio::run(fut);
```

You can see the lack of published ports with `docker ps -a`
```
PORTS                      NAMES
                           svc-test-shiplift
0.0.0.0:63999->63999/tcp   svc-test-cmd
```

**Comment by softprops** [comment]
I would be open to a pull request to add this feature
