### ISSUE TITLE
Support for bind mounts?

### ISSUE THREAD

**Issue by keirlawson** [softprops/shiplift#163]
So far as I can see Shiplift does not support bind mounts (https://docs.docker.com/storage/bind-mounts/) only named volumes, is this the case? Would it be possible to add bind mounts support if it is missing?

**Comment by schrieveslaach** [comment]
I think that you can just use the path to file/directory you want to mount:

```
docker
    .containers()
    .create(&ContainerOptions::builder(image.as_ref()).volumes(vec!["/path/to/file:/path/in/container"]).build())
```

**Comment by keirlawson** [comment]
Ah yep confirmed you can, had assumed that option was for named volumes, will open a PR to add some clarificatory documentation.
