### ISSUE TITLE
http::Uri instead of url::Url

### ISSUE THREAD

**Issue by mfirry** [softprops/shiplift#183]
- Crate version: 0.5
- OS: macOS Mojave (10.14.5)
- Output of running `docker version` on the command line:
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Instead of
```
use url::Url;

let docker = Docker::host(Url::parse("http://yourhost").unwrap());
```

I think one should do
```
use http::Uri;

let docker = Docker::host("http://yourhost".parse::<Uri>().unwrap());
```

**Comment by schrieveslaach** [comment]
I think that the [url](https://docs.rs/url/1.7.2/url/) is a much smaller library and should be a perfect match here because it is only required to parse an URL. The [http](https://docs.rs/http/0.1.17/http/) provides much more type types that are not required for the use cases of shiplift.

**Comment by mfirry** [comment]
I'm confused now. I opened the issue because for me `Url` wasn't working and I had errors saying I should provide a `Uri`. Am I missing something?

**Comment by schrieveslaach** [comment]
Ah, okay, I messed up the issue description and I thought you suggested to use `http::Uri` instead `url::Url`. I agree that `url::Url` is the much better choice.

**Comment by danieleades** [comment]
@schrieveslaach `http` is a transitive dependency of `hyper` anyway, no?

**Comment by schrieveslaach** [comment]
Yes, [`hyper` relies on `http`](https://github.com/hyperium/hyper/blob/master/Cargo.toml#L27)

**Comment by danieleades** [comment]
What I mean is, it doesn't matter whether it has extra types or functionality you don't need, since it's statically linked already, so no matter how lightweight `Url` is, it's duplicated functionality. Is it more ergonomic for parsing url strings in some way than the `http` types?

**Comment by schrieveslaach** [comment]
I think the issue here is that the `http` crate does not include any URL type. It include only an URI type. URIs are the super type of URL (see [here](https://danielmiessler.com/study/url-uri/)) and in the desribed use case only URLs are valid input parameters. Therefore, IMHO `shiplift` should express that restriction through good parameter types.

**Comment by mfirry** [comment]
My original issue is basically that if I try and do what the README says
```
use url::Url;

let docker = Docker::host(Url::parse("http://yourhost").unwrap());
```

I get ```expected struct http::uri::Uri, found struct url::Url```

**Comment by thomaseizinger** [comment]
> My original issue is basically that if I try and do what the README says
> 
> ```
> use url::Url;
> 
> let docker = Docker::host(Url::parse("http://yourhost").unwrap());
> ```
> 
> I get `expected struct http::uri::Uri, found struct url::Url`

I've filed a PR that fixes this documentation error: https://github.com/softprops/shiplift/pull/207
