### ISSUE TITLE
Add Chrono Feature

### ISSUE THREAD

**Issue by schrieveslaach** [softprops/shiplift#186]
The crate [`chrono`](https://docs.rs/chrono/0.4.7/chrono/) supports parsing of date times in RFC3339 format and the Docker API uses this format e.g. to desribe the start time of a container. I would be vary handy if `shiplift` would have an optional feature to deserialize these fields as `DateTime<FixedOffset>`. For example, this PR aixigo/PREvant#13 would benefit from direct support of chrono.

**Comment by softprops** [comment]
I would be open to a pr to add this feature

**Comment by schrieveslaach** [comment]
I can make the PR. Should one question up front. Do you think it should be a feature toggle or do you think chrono should be supported by default?

**Comment by softprops** [comment]
I would say a feature toggles that's on by default with the option to turn off would be generally ideal but I'd also be find without a toggle since chrono is pretty ubiquitous in the ecosystem

**Comment by schrieveslaach** [comment]
@softprops, there is a PR implementing deserialization with `chrono`.
