### ISSUE TITLE
Detect tls stream and use `https` scheme instead of provided `tcp`

### ISSUE THREAD

**Issue by LucioFranco** [softprops/shiplift#192]
When attempting to use shiplift in a circleci environment with hyper, it must use `tcp` to connect to the remote docker daemon. This requires tls via the docker docs. The issue arises here https://github.com/softprops/shiplift/blob/master/src/transport.rs#L166 when the `tcp://` scheme is copied. The real problem is that hyper's version checking requires the use of `https` instead of `tcp` directly. Thus the fix here is to replace the scheme only when encrypted.

Reference failing tests in https://github.com/timberio/vector/pull/787

**Comment by elihunter173** [comment]
Should this issue still be open?

**Comment by LucioFranco** [comment]
I think its been fixed!
