### ISSUE TITLE
Inconsistencies between builder interfaces

### ISSUE THREAD

**Issue by colvinwellborn** [softprops/shiplift#210]
The `shiplift::builder::ContainerListOptionsBuilder::all()` method does not accept a boolean argument, assuming the value should be the string `"true"`. However, `shiplift::builder::ImageListOptionsBuilder::all()` takes a boolean argument, which it converts to a string. It would be nice if these were consistent.

I didn't check other builders, since those were the only two I was concerned with, but it is possible that there are other instances of the inconsistency.

**Comment by colvin** [comment]
See https://github.com/softprops/shiplift/pull/211

**Comment by softprops** [comment]
@colvinwellborn nice find. This repo has many varied contributors. It's possible the interfaces were submitted by different folks.

**Comment by colvin** [comment]
@softprops This was merged in #211, so this issue should be closed.
