### ISSUE TITLE
Request to add the 'PublishAllPorts' option to the ContainerOptionsBuilder

### ISSUE THREAD

**Issue by tylerhjones** [softprops/shiplift#214]
I am using dockertest-rs in my integration tests. After trying to manage locks and host:port mappings, the maintainer pointed out to me that docker now has a 'PublishAllPorts' option available. This option will assign an available host port at random for each exposed port on the container. The ContainerOptionsBuilder does not currently support this option.

[Documented Option](https://docs.docker.com/engine/api/v1.39/#operation/ContainerCreate), search for 'PublishAllPorts'

I would like to add this to the ContainerOptionsBuilder by introducing code such as

```rust
    pub fn publish_all_ports(
        &mut self,
    ) -> &mut Self {
        self.params.insert("HostConfig.PublishAllPorts", json!(true));
        self
    }
```

```rust
    /// Test container option PublishAllPorts
    #[test]
    fn container_options_publish_all_ports() {
        let options = ContainerOptionsBuilder::new("test_image")
            .publish_all_ports()
            .build();

        assert_eq!(
            r#"{"HostConfig":{"PublishAllPorts":true},"Image":"test_image"}"#,
            options.serialize().unwrap()
        );
    }
```

**Comment by softprops** [comment]
Looks great @tylerhjones
