### ISSUE TITLE
Updated examples to use tokio 0.2.x

### ISSUE THREAD

**Issue by madelaney** [softprops/shiplift#228]
I'm new to rust and I'm looking at using shiplift with tokio 0.2.x but the examples that exist are targeted for tokio 0.1.x. However, the latest version of tokio is 0.2.x and some of the functions that you use, mainly `tokio::run`, are no longer supported.

The example that comes to mind is the simple [images.rs](https://github.com/softprops/shiplift/blob/master/examples/images.rs).

Any help would be awesome.

**Comment by softprops** [comment]
There would need to be some refactoring to upgrade tokio before updating examples.

**Comment by madelaney** [comment]
Okay, I can downgrade to tokio 0.1.x since my usage is pretty simple. Thanks for getting back to me.

**Comment by softprops** [comment]
Thanks for the nudge though. This is on my list of things to do

**Comment by tjtelan** [comment]
@madelaney For what it's worth, so you don't end up writing a lot of new code on old tokio while learning Rust, I end up using tokio 0.1.x just for Shiplift and 0.2.x everywhere else.

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml

```
[dependencies]
shiplift = "0.6"
tokio_01 = { package = "tokio", version = "0.1" }
tokio = "0.2"
```

**Comment by schrieveslaach** [comment]
@softprops, do you have any plans to merge #191 to support tokio 0.2?

**Comment by softprops** [comment]
@schrieveslaach that branch seems to have conflicts. Let me check in with the author
