### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by tofay** [softprops/shiplift#235]
Is there a timeline for the next shiplift release? I'm keen to use both https://github.com/softprops/shiplift/pull/229 and https://github.com/softprops/shiplift/pull/220 in a released version.

**Comment by matthiasbeyer** [comment]
Any updates on this? Especially since tokio 1.0 is out?

**Comment by softprops** [comment]
I'll need to construct a Changelog first. Any help on this is welcomed help

**Comment by andraprs** [comment]
Can you please publish "0.7.0" release on crates.io as well. Thank you.

**Comment by petreeftime** [comment]
There is an advisory out for the hyper version used by the 0.6.0 release: https://rustsec.org/advisories/RUSTSEC-2021-0020. The 0.7.0 release seems to fix this.

**Comment by matthiasbeyer** [comment]
On 08-02-2021 01:00:55, petreeftime wrote:
> There is an advisory out for the hyper version used by the 0.6.0 release:
> https://rustsec.org/advisories/RUSTSEC-2021-0020.

Maybe it is still a good idea to publish a 0.6.1 with a fixed hyper version (if
there is one).

**Comment by elihunter173** [comment]
I don't see a reason to not go directly to 0.7.0. AFAIK the changelog is complete and the API is sufficiently tested since a fair number of people follow the master to get access to tokio 1.0 and async-await (https://github.com/softprops/shiplift/issues/230)

**Comment by matthiasbeyer** [comment]
On 08-02-2021 08:29:42, Eli W. Hunter wrote:
> I don't see a reason to not go directly to 0.7.0. 

Depends on the API changes, I am not up to date whether there are any.
If not, there's of course no reason to not update immediately.
If there are, users might want to continue using 0.6.x for a certain amount of
time.

But of course, as you said, most are tracking master anyways (so am I).

**Comment by softprops** [comment]
published 0.7.0. will be working on what would hopefully be a quick follow up after I work my way through the merge queue
