### ISSUE TITLE
Refactor Modules by API Endpoint

### ISSUE THREAD

**Issue by elihunter173** [softprops/shiplift#257]
Currently a lot of functionality is split between `lib.rs` and `builder.rs`. I think it would make sense to split functionality into modules based off of their endpoint they hit (e.g. `container.rs` and `image.rs`) since that should make it easier for maintainers to maintain and new members to navigate the docs. We could keep most of the API somewhat unchanged through re-exports.

I plan to take this on if there's interest coming by wanted to make sure before I sent the PR in.

**Comment by wojciechkepka** [comment]
I had the same thoughts recently so I'm all for this change. I must say it would make it much clearer to navigate the code base.
