### ISSUE TITLE
Add a link to Docker api reference on each api endpoint in this library

### ISSUE THREAD

**Issue by wojciechkepka** [softprops/shiplift#259]
I had some initial attempts at adding hyperlinks to Docker API Reference in #255 but we came to the agreement that using a macro like my proposed `api_doc!` that would wrap a struct or a function and annotate it with extra `#[doc = ""]` attributes was making the code unreadable and broke rustfmt.

Perhaps there is another approach to this problem. I see this as a nice quality of life improvement to reading the docs and I think its worth the effort to automatize it (maybe with a proc macro?)

**Comment by matthiasbeyer** [comment]
Are you still planing to approach this, even though your PRs were closed unmerged? :pray:

**Comment by wojciechkepka** [comment]
Well I would definitely be interested but perhaps first we could come up with a proper way to add this before I submit any changes.

**Comment by elihunter173** [comment]
I think I mentioned it earlier, but I think a line like this at the end of doc comments would be sufficient since the API links are unlikely to change and even if they do a simple sed / search and replace should be able to find them all pretty easily.

```rust
/// [API Reference](api-link)
```
