### ISSUE TITLE
Why does `Containers::get()` not return Option?

### ISSUE THREAD

**Issue by matthiasbeyer** [softprops/shiplift#275]
Hi,

I don't understand why `Containers::get()` does not return an `Option<Container>`. From what I understand, `get()`ing a container by name (which seems to be the argument here) would either return an instance of `Container` or `None` if the named container does not exist.

But the interface does not return an `Option` but simply an instance of `Container`.

I don't understand why.
Maybe the docs are missing something here, maybe I just don't understand.

Can someone please elaborate or, if applicable, fix the documentation/interface?

**Comment by elihunter173** [comment]
Currently `Containers::get()` directly passes the name you provide to `Container::new()` as the ID, so it doesn't do any validation on the name to ensure the container exists, just returns a potentially invalid handles. The docs are definitely lack-luster in this regard and should be improved.

I think it would be a good idea to make it so `Containers::get()` would actually convert the name you provide to an ID and return `Some(Container)` if it is successful or `None` if it cannot find the container.

**Comment by matthiasbeyer** [comment]
I consider this solved with the two PRs merged.
