### ISSUE TITLE
[Help] Get stats from more than one container at same time

### ISSUE THREAD

**Issue by GitKalle** [softprops/shiplift#283]
I'm in the beginning of learning Rust. I read the official book and work on a little project to get graphs about the used resources of my Docker containers.

I get the stats from one container successfully. I used the example [stats.rs](https://github.com/softprops/shiplift/blob/master/examples/stats.rs) from this repository. Now I try to get the stats from all containers at the same time. That's why my question:

How can I get stats from more than one container at the same time?

**Comment by wojciechkepka** [comment]
One way I could come up with is this:

## cargo.toml
```toml
[dependencies]
shiplift = "0.7"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
futures = "0.3"
```

## main.rs
```rust
use futures::stream::StreamExt;
use shiplift::{Container, ContainerListOptions, Docker};

#[tokio::main]
async fn main() {
    let docker = Docker::new();
    let containers_api = docker.containers();
    let opts = ContainerListOptions::builder().all().build();

    // handles to all containers in docker
    let handles: Vec<Container> = containers_api
        .list(&opts)
        .await
        .unwrap()
        .into_iter()
        .map(|container| containers_api.get(container.id))
        .collect();

    for handle in handles {
        if let Some(stats) = handle.stats().next().await {
            //...
        }
    }
}
```
You could then `push` all the stats to a `Vec` or process them however else you like.

**Comment by GitKalle** [comment]
Thank you very much. I have a look on it.
