### ISSUE TITLE
exec should return output

### ISSUE THREAD

**Issue by tshepang** [softprops/shiplift#50]
The return type for calling `exec` is `Result<()>`, meaning it doesn't return any output at all.

**Comment by softprops** [comment]
Just haven't come up with an agreeable interface just yet

**Comment by stephanbuys** [comment]
@softprops, tested @Joxit's solution and it works great for our usecase, so +1 from me for this interface even if it changes later it is something to use in the meantime.

**Comment by softprops** [comment]
Just published 0.3.2 which should have all of these changes in https://github.com/softprops/shiplift/blob/master/examples/containerexec.rs#L15-L21.
