### ISSUE TITLE
Implement export

### ISSUE THREAD

**Issue by softprops** [softprops/shiplift#6]

**Comment by elihunter173** [comment]
Should this be closed?

https://github.com/softprops/shiplift/blob/4e3f69c34a177697af940849fced1a284fc09449/src/lib.rs#L117-L124 https://github.com/softprops/shiplift/blob/4e3f69c34a177697af940849fced1a284fc09449/src/lib.rs#L234-L247

**Comment by matthiasbeyer** [comment]
I'll close this now, feel free to reopen if needed.
