### ISSUE TITLE
Use error chain for deriving errors

### ISSUE THREAD

**Issue by softprops** [softprops/shiplift#62]
Error chain is a very common errors handling crate that has a good ecosystem going for it. This library could benefit from being a friendly actor in that ecosystem

**Comment by Phrohdoh** [comment]
Consider the new crate [`failure`](https://crates.io/crates/failure) too.

**Comment by matthiasbeyer** [comment]
We talked about error handling crates in #242 and concluded on not using an error helper lib. I'll therefore close this now.
