### ISSUE TITLE
Unfriendly API?

### ISSUE THREAD

**Issue by lnicola** [softprops/shiplift#63]
Consider the following function:

```rust
fn make_container<'b>(containers: &'b Containers) -> Container<'b, 'b> {
    let cont_opts = ContainerOptions::builder("alpine")
        .cmd(vec!["true"])
        .build();
    let cont_info = containers.create(&cont_opts).unwrap();
    containers.get(&cont_info.Id)
}
```

It doesn't compile because the returned `Container` needs to have a reference to its `Id`. I'm not sure if it's even possible to do this.

Having more structs that own their data might make the API a bit easier to use.

**Comment by matthiasbeyer** [comment]
This seems to be not relevant anymore, as the API changed since. Feel free to reopen if you see need.
