### ISSUE TITLE
Panic when building a new image

### ISSUE THREAD

**Issue by petehayes102** [softprops/shiplift#65]
When running `docker.images().build(...)`, it ends up panicking with this message:
>expected build output stream or error

This is because one of the JSON objects is not a "stream", "status" or "error":
>DEBUG:shiplift: Object({"aux": Object({"ID": String("sha256:3fdcaf0ab1b77ae77395563c779592fa6c00b210c38d5f83c6b01d5da2ccf2df")})})

Instead of identifying and repackaging each object, would it be better to simply return the JSON iterator? As far as I can tell, there isn't any value added by trying to repackage the objects into native structures. I also can't find a spec for the response JSON, so this issue might keep popping up over time. Manual doesn't help: https://docs.docker.com/engine/api/v1.31/#operation/ImageBuild

**Comment by softprops** [comment]
I agree there have been a number of issues that have popped up like this in the past. I'll take note of this

**Comment by petehayes102** [comment]
Cool. I solved it in my code by simply removing the map() fn, which also made the code a lot more readable. Would you accept a PR or do you want to consider other options?

**Comment by softprops** [comment]
Absolutely open to prs. There's a longer term plan of upgrading to newer versions of hyper and serde which would allow for other things to happen and would definitely be breaking changes but if there are midterm solutions to current problems I accepts prs with open arms!
