### ISSUE TITLE
Filter on multiples events of the same type

### ISSUE THREAD

**Issue by jagu-sayan** [softprops/shiplift#67]
It's an awesome feature if we can listen on multiples events of the same type.

Like describe in [docker-cli events](https://docs.docker.com/engine/reference/commandline/events/) command.
```
Using the same filter multiple times will be handled as a OR;
for example --filter container=588a23dac085 --filter container=a8f7720b8c22
will display events for container 588a23dac085 OR container a8f7720b8c22
```

In this example, I want all container events that `start`, `stop` or `die`. But I only get  `die` event.
[Look documentation](http://lessis.me/shiplift/shiplift/builder/enum.EventFilter.html)
```rust
use shiplift::builder::EventsOptions;
use shiplift::builder::EventFilterType;
use shiplift::builder::EventFilter;

let mut options = EventsOptions::builder();
options.filter(vec![
    EventFilter::Type(EventFilterType::Container),
    EventFilter::Event("start".to_string()),
]);
options.filter(vec![
    EventFilter::Event("stop".to_string()),
]);
options.filter(vec![
   EventFilter::Event("die".to_string()),
]);
```

This is due to [internal implementation](https://github.com/softprops/shiplift/blob/1d95f805f1287aac532d04e7d3b7351d72f16950/src/builder.rs#L685) that only send one `filters` parameter to docker daemon.

**Comment by jagu-sayan** [comment]
With this fix, you can now do
```rust
use shiplift::builder::EventsOptions;
use shiplift::builder::EventFilterType;
use shiplift::builder::EventFilter;

let mut options = EventsOptions::builder();
options.filter(vec![
    EventFilter::Type(EventFilterType::Container),
    EventFilter::Event("start".to_string()),
    EventFilter::Event("stop".to_string()),
    EventFilter::Event("die".to_string()),
]);
```
and get `start`, `stop` and `die` event of containers (and not only `die` event)

**Comment by jagu-sayan** [comment]
@softprops ping

**Comment by Nurrl** [comment]
Is this issue can be closed ? It seems to be merged :D

**Comment by jagu-sayan** [comment]
@Nurrl  Yes :)
