### ISSUE TITLE
support docker pull/push from private registry?

### ISSUE THREAD

**Issue by timzaak** [softprops/shiplift#80]
Is there any plan to support docker pull/push from private registry?
It should add a header in the http request, But it is no easy to do so, it needs lots of changes.

**Comment by smithwinston** [comment]
I think this just needs to have a way to specify credentials in the configuration and supply that as needed to the registry via the `X-Registry-Auth` header on the REST requests.

**Comment by softprops** [comment]
I haven't looked into this mysql but I'd be open to a pr
